### ISSUE TITLE
If "Save original filename" is disabled and you download a album its still downloads the original name.

### ISSUE THREAD

**Issue by WhyANameWhy** [chandevel/Clover#155]
So if "Save original filename" is disabled and you download a album its still downloads the original name. If i activate it nothing changes.

**Comment by Floens** [comment]
Copying my response from the pr #159 
>The reason that album downloads always use the name 4chan provides is because this way the downloader can skip over existing images reliably. If you use the other name and when there are duplicate file names the second one wouldn't be downloaden. I can solve this by doing some md5 checking. But that's the reason why I didn't do this.

There are several options, like inspecting the md5 of the image when it encounters duplicates, or saving what was downloaded in the db.

**Comment by hardliner5000** [comment]
Adding a _1, _2, _3, to the dublicate filename would be possible?

**Comment by Floens** [comment]
Also, the term "original filename" is ambiguous. It could mean the name from the poster of from the server. It's interpreted as the server name now.

>Adding a _1, _2, _3, to the dublicate filename would be possible?
Yes, but that's not the issue here. The single image saver adds _n to the filename if it already existed, but we want the album downloader to skip images it already downloaded. This cannot be done reliably if we use the filename that is user generated. This because someone can post the same "image.jpg" image 5 times and then only the first would be downloaded because it would get seen as already downloaded.
It's now always using the name from 4chan as a workaround, since those are always unique.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

**Comment by cm-mc** [comment]
Shouldn't that better be left for the user to decide whether to dl chan server filename or the original uploaded filename (using file_n), specially since you can already do that for single file dl?
I was looking for a reader that did this AND allowed to dl all board files at once, and was hoping clover was the one...

**Comment by CatKasha** [comment]
What if use both `tim` and `filename` value in name of file?
Example: `tim.filename.jpg`
After value `tim` use symbol for separation like dot, and after dot add first 100-150 letters of `filename`

**Comment by bearstampede** [comment]
I almost posted a duplicate-duplicate request for this feature. Floens pls, this would provide value for research.
