### ISSUE TITLE
Reupload to Google Play

### ISSUE THREAD

**Issue by Floens** [chandevel/Clover#264]
Upload Clover to Google Play again.

Clover can be reuploaded to Google Play if we restrict what we can see by default. Making Clover to act more as a generic browser is our target.

This issue is blocked on multisite support #263

Ideally we want a Googler to check if Clover is compliant before uploading again.

**Comment by ParkerK** [comment]
I think you can do this if you do something like Reddit Sync does, have a few SFW boards by default, and make the user add any other boards (be they SFW or NSFW). I think the main issue with Clover is that you can select any of the boards from the dropdown list, instead of user manually having to enter them
