### ISSUE TITLE
Links and post references are followed in spoilered text at first press

### ISSUE THREAD

**Issue by Wesmania** [chandevel/Clover#500]
When clicking on spoilered text in order to show it, if there is a link or a post reference under the cursor, it will be followed immediately. It's not expected behaviour since you can't tell if a link is there before you show the spoiled text.

Android version: 7.1.1
Phone model: SM-J510FN
Clover version: v3.0.1 F-Droid

**Comment by EfronC** [comment]
Same issue, and is very bad since could cause to open a malicious link by accident. A way I have to evade is: Instead of pressing the spoiler, just keep pressing, and it will show what is under it, that way you can know if its a link or not, if it's not a link, you put up your finger and the spoiler will be showed, if it's a link and you don't want to open it, without stop pressing, move your finger a little, the spoiler will appear again, and you will be able to put up your finger without opening the link.

It's an easy solution while we wait this problem is solved.
