### ISSUE TITLE
App crashing extremely frequently in thread

### ISSUE THREAD

**Issue by JustAnotherAnonorig** [chandevel/Clover#546]
My app crashes frequently while in thread, easily once every 5-10 minutes

While browsing a thread (not in the catalogue) my app will randomly freeze up and become unresponsive. If I exit the app and attempt to restart it I will simply get an unresponsive white screen. The only fix for this seems to be clearing cache, which will temporarily solve the issue, only for it to happen again 5-10 minutes later. I am using a Redmi note 3.

Android version: 5.0.2 LRx22G
Phone model: Redmi Note 3
Clover version: latest clover dev (v3.0.1-977c5a1f), this problem has persisted for multiple builds though

**Comment by Riotous** [comment]
@JustAnotherAnonorig Question: why is your Redmi Note 3 still at 5.0.2? Your phone's official ROM is at 6.x 

Perhaps you should make sure you have the latest official update for your phone before reporting issues because I have never had any issues with Clover freezing up on the 3 phones I've used it on, all running the latest OS available at the time, both official and custom ROMs.

**Comment by JustAnotherAnonorig** [comment]
The MediaTek version of the Redmi note 3 does not have an android 6.0.1 update, that's only for the Note 3 SE & SD variants . I am using the latest official update.
