### ISSUE TITLE
Indentation on posts with images = wasted space?

### ISSUE THREAD

**Issue by Astridchan** [chandevel/Clover#585]
I recently saw this thread on /g/:
https://warosu.org/g/thread/S68345886

And in the OP there was this image with Dashchan (I think) on the left and Clover on the right:

![1541293166099](https://user-images.githubusercontent.com/40862101/48001142-5d8c4400-e110-11e8-9840-460995d8ecbf.jpg)

Several comments in that thread pointed out something to me that I hadn't noticed before but that I now cannot unsee: Any post with with an image attached will have the text indented so there is a column of empty space beneath the image. This is especially noticeable on longer posts. Is there a reason for this? As it currently stands, it just seems to be wasted space to me.

Another example with 4chan.org/g on mobile browser vs. Clover:

![photo collage_20181105_160015881](https://user-images.githubusercontent.com/40862101/48002385-1a33d480-e114-11e8-9761-1691654cbc8a.jpg)

**Comment by Floens** [comment]
It's partly a technical issue, and partly design.
As you can see, Dashchan splits up the meta stuff and the post title & text, while Clover shows the text at the top. This is for a reason: text wrapping around an image is difficult to do in Android. Splitting up the layout into different TextViews is easier. I've looked into text wrapping before, but it's not easy to do. And there is also a performance impact with the text wrapping methods I saw.

Now, most of the time the padding isn't an issue because posts aren't that long, but with such a long post as the one you gave it looks pretty bad.
The start of the post text used to be a little higher, but with the default setting of showing the file name the text also starts at almost the same height as the thumbnail.

We could change the layout to be like dashchan where we split up the textviews and start the textview below the thumbnail. I'm not sure if that looks good on posts that have a short post text.

**Comment by Astridchan** [comment]
I see. I was thinking that simply wrapping the text around the thumbnail would be the ideal solution, I guess I now know why neither app is doing that.

> We could change the layout to be like dashchan where we split up the textviews and start the textview below the thumbnail. I'm not sure if that looks good on posts that have a short post text.

We're getting into subjective territory here regarding design choices, but I really don't think it looks bad at all, even in short posts:

![example1](https://user-images.githubusercontent.com/40862101/48025343-ccd35980-e14b-11e8-9809-e15f407e54b3.png)

Only downside I can see is that slightly more space is taken vertically, even with the smaller thumbnail size in Dashchan. And the example above really shows the best case scenario for Clover, where the post is short enough that no padding is needed. If you look at the screenshot below, the first post with an image attached already has some padding on it, even though it's a post with only a single line of text. And in the second post there is already a significant amount of padding with three lines of text. Another thing I wanted to highlight in the screenshot with the red line is how text in Dashchan is always aligned to the left edge, which in my opinion feels more continous and less jarring than having the alignment of the text change depending on whether there is an attachment or not.

![example2](https://user-images.githubusercontent.com/40862101/48024795-33577800-e14a-11e8-8498-7635acb08bcb.png)
