### ISSUE TITLE
LynxChan support

### ISSUE THREAD

**Issue by StephenLynx** [chandevel/Clover#594]
I'm the developer of lynxchan and the engine is getting some traction: http://lynxhub.com/lynxchan/res/285.html

So i'd like to contribute or support with the development of support for the format I use. I know my way around native android development but haven't touched it in 4 years tho.

**Comment by Floens** [comment]
The lynxchan engine is a bit different than other engines so it should get its own module, not extend from futuba or vichan.

I still want to implement the well-known thing, so that Clover can detect what engine is running on the site.
I suggest the following, see also #263:
Have a .json endpoint at the following path: `/.well-known/engine.json` with the following content:
```
{
  "version": "1",
  "engine": "lynxchan",
  "configuration": {
    "someKey": "someValue",
    ...
  }
}
```

That's something basic we can work with. We'll make this api formal later. After this we can add a detection feature and a module for the lynxchan engine.

**Comment by StephenLynx** [comment]
LynxChan can already provide information about itself on /index.json with the field "version" containing a string, so that won't be necessary.

**Comment by TheStranjer** [comment]
Seconding that LynxChan support would be fantastic.
