### ISSUE TITLE
Spoiler on notification

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#598]
It appears that, on boards that come with spoiler function, when someone post something that contain spoiler tag and it goes up to clover's notification, the spoiler tag would be ignored and its content would be directly exposed. Please allow changing this behavior and also consider changing the default behavior.

**Comment by Adamantcheese** [comment]
Note for other people trying to do this: while SpannableStrings do render in notifications, there are several things preventing this from being easy to fix. Notably, spoilers are PostLinkables and the replaceAll(">$1") call in WatchNotifier changes all CharSequence objects to String, removing any text display spans attached to the text. Because a spoiler can have a link under it, you can't easily split up the string and do the modifications to it, as putting the spans back on wouldn't line up any more.

A possible solution is to parse a "notification ready" comment and store it with the Post object via the builder, but that might be too much data to keep stored. Also the Post.Builder method comment(String comment) should be refactored to comment(CharSequence comment) to ensure spans aren't deleted.
